# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f5d0913d72d7e13399de7c881da06507941cd6b64b8baef127be619da88df82d3978b452e7d8fff3c1b06e8ce22751cf632bc9764b541fe037d9d00e53878fc

test:
  secret_key_base: 548a8b54954b1fcb23e660845a9a154298a9732d3036b0600139bc5eaae0915bf0cb18776253d1684832e7113ef7b66a4d7b5dba9a1c2b99f127e7fda157dcbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
